- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - gnupg
    state: present
    update_cache: true

- name: Add Grafana GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  become: true
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true

- name: Start and enable Grafana
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
